export const GET_ATTENDEES_EVENT = "GET_ATTENDEES_EVENT";
export const GET_ATTENDEES_USER = "GET_ATTENDEES_USER";
export const STORE_ATTENDEES = "STORE_ATTENDEES";
export const REMOVE_ATTENDEES = "REMOVE_ATTENDEES";
export const REMOVE_ATTENDEES_DATE = "REMOVE_ATTENDEES_DATE";
export const REMOVE_ATTENDEES_EVENT = "REMOVE_ATTENDEES_EVENT";
